### ISSUE TITLE
Updates through web browser show bad auth

### ISSUE THREAD

**Issue by indigo423** [ddserver/ddserver#26]
If you update a hostname through URL

https://{user}:{pass}@dyn.c4fd.org/nic/update?hostname=blafoo.dyn.c4fd.org&myip=1.2.3.4

returns with bad auth error

**Comment by fooker** [comment]
This was never intended to work.

It seems like firefox is not passing the BasicAuth header if the site does not answer an unauthorized request with a 401 error.

I've added two additional GET parameters ''username' and 'password' which are evaluated if the BasicAuth header is empty.

Fixed by #53.
