### ISSUE TITLE
Fix setup.py

### ISSUE THREAD

**Issue by reissmann** [ddserver/ddserver#27]
The setup.py file is non-optimal at the moment and should be fixed.

**Comment by indigo423** [comment]
Unsolvable issue.

**Comment by fooker** [comment]
The fuck-ups in the current state of setup.py are to obvious - so there was no reason to note them...

**Comment by reissmann** [comment]
Like fooker commented, there are some obvious "don'ts" in the current setup.py file. The file only has about 100 lines, so if you look at it (and you ever wrote a setup.py file), you should be able to recognize the issues. Marking this issue invalid really doesn't help too much.

**Comment by indigo423** [comment]
It helps opening issues with a title and description which can be solved directly. It gives also others the possibility to contribute. If there are more issues in setup.py, then it helps to split them up in separate issues which can be solved, even by more then just one person. Well described issues can be the entry especially for new people in the project, cause they can get an idea about how complex an issue is and can start to learn and contribute.
