### ISSUE TITLE
Disable hosts not updated

### ISSUE THREAD

**Issue by reissmann** [ddserver/ddserver#39]
Hostnames, which are not updated for a configurable period of time, should be disabled and a note (i.e. an email) should be sent to the owner of the hostname.

**Comment by fooker** [comment]
There are ISPs that do not do a forced disconnect (i.e. the german cabel internet providers) but do have dynamic IP assignment for their clients. This can result in very long periods of unchanged IPs but will result in a change on external events like power outages or administrativ modem reconnects.

**Comment by fooker** [comment]
At least, we should record the date of the last activity. Based on that we could provide a maintenance script disabling all hosts not updated in a specific period.

**Comment by fooker** [comment]
In adition, we should show the last activity date in the admin panel

**Comment by reissmann** [comment]
Looks like we already do this :) Let's leave it with logging the last update.
