### ISSUE TITLE
Access the WebUI

### ISSUE THREAD

**Issue by Jzarecta** [ddserver/ddserver#48]
Hi I need information on how to access the webui for ddserver. The documentation don't specify a default port, I will assume is the default for flask, but would be good if there was some indication after running ddserver saying please verify the installation at localhost:YXZ etc.

**Comment by reissmann** [comment]
Hi,

sorry for the messy documentation. If not configured, ddserver will listen on 0.0.0.0:8080.

You can specify this in the configuration file /etc/ddserver/ddserver.conf. Have a look at ddserver/resources/doc/ddserver.conf.example.
