### ISSUE TITLE
error: Couldn't find a setup script in /tmp/easy_install

### ISSUE THREAD

**Issue by intelyes** [ddserver/ddserver#76]
after installing all Prerequisites and start with "python setup.py install",  the process stops with the error message
"error: Could not find a setup script in /tmp/easy_install-FFO6CD/require-0.1.1.linux-x86_64.tar.gz" 
why like this ?

**Comment by reissmann** [comment]
I guess you installed/clones from master? I accidentally commited stuff there, which was not tested. I'm sorry for this ... 

Please try again using the latest release v0.2 (https://github.com/ddserver/ddserver/releases) or go back by three commits in branch master (git checkout 18e13e) before you run setup.py

@fooker do you know anything about the error message regarding require? Will we have this issue in v0.3?

**Comment by intelyes** [comment]
Hay Reissmann...
 to meet you, and thank you very much for enlightenment, I will try it again using the instructions you give, hopefully this time it will go well. Once again thank you...

Success also for you.

**Comment by reissmann** [comment]
Reverted master to v0.2

Please reopen this issue, if you still experience problems.

**Comment by masrony** [comment]
Hey Rissmann...
after following the instructions from you, I managed to install smoothly, there is now a new problem, each machine runs reboot, ddserver can not see it, and I have to restart it via command line, is this normal?

**Comment by intelyes** [comment]
I am sorry Rissmann, the last friend I leave a comment ....
exactly what my friend said earlier, and I not successful email configuration verification, whether there is an email configuration instructions for more details?

**Comment by reissmann** [comment]
I'm not exactly sure if I understand your problem right.

First, running ddserver on a VPS should just work fine. I'm doing the same.

On the reboot issue: There are example init-scripts in the subdirectory ddserver/resources/doc/. One of this scripts should be installed in your /etc/init.d directory, allowing you to start ddserver by issuing the command /etc/init.d/ddserver start. If this works, please verify to enable the service to autostart on boot (i.e., on a debian-based system by using the command update-rc.d)

I'm not getting the email question. Mails are sent using the systems mailsystem. If your server is able to send out email, ddserver should also be (i.e., install postfix, exim, or any other MTA). 

In case you didn't find it so far, there is some (but not too much) documentation at https://ddserver.0x80.io/index.py/Documentation

**Comment by intelyes** [comment]
- This is what I mean with a configuration that has not been successful email
wherein when there is a user to create an account (it can not be verified)
![screenshot 1](https://cloud.githubusercontent.com/assets/12556502/8079417/715ea024-0f8e-11e5-95a6-7734ed5c5ffa.png)

- And this is when admin activation new user (activation undeliverable)
![screenshot 3](https://cloud.githubusercontent.com/assets/12556502/8079482/f002adb2-0f8e-11e5-94bf-d4562fb60a59.png)

**Comment by reissmann** [comment]
Could you please verify that there is a local SMTP server running?

When using a command like this:

    netstat -anptl |grep 25

the output should include something like this:

    tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      15312/master

**Comment by intelyes** [comment]
- Less than one more step.
- Everything is configured such plans, the user registers already ok, email delivery is ok, ports on clien already open, all is going well, IP update on the server already looks good ...... but why would not remotely ddserver its clien.

- Whether there should be a configuration file (ddclient.conf), and should be placed where ?

- Am I too stupid so could not solve this, he ... he ... he ...

**Comment by intelyes** [comment]
This log on command 'ddserver-bundle'
--------------------------------------------------

root@cloud:~# ddserver-bundle
Bottle v0.12.8 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/usr/local/bin/ddserver-bundle", line 9, in <module>
    load_entry_point('ddserver==0.2', 'console_scripts', 'ddserver-bundle')()
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.2-py2.7.egg/ddserver/utils/deps.py", line 129, in wrapped
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.2-py2.7.egg/ddserver/__main__.py", line 39, in main
    web.run()
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.2-py2.7.egg/ddserver/utils/deps.py", line 129, in wrapped
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ddserver-0.2-py2.7.egg/ddserver/web.py", line 77, in run
    debug = config.wsgi.debug)
  File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.8-py2.7.egg/EGG-INFO/scripts/bottle.py", line 3117, in run
    server.run(app)
  File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.8-py2.7.egg/EGG-INFO/scripts/bottle.py", line 2771, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 144, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
root@cloud:~#

**Comment by intelyes** [comment]
And this log on file 'ddserver.log'
----------------------------------------
registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>

**Comment by reissmann** [comment]
It says :

     socket.error: [Errno 98] Address already in use

This means, there is already an application listening on port 8080. Is ddserver already running? Or is there another application (i.e., apache webserver) on this port?

Try this command to find out what application is listening on the port:

    netstat -anptl |grep 8080

**Comment by reissmann** [comment]
Whether there should be a configuration file (ddclient.conf), and where should be placed ?

This is just an example and not needed by ddserver. You can install ddclient on your home-computer to send your IP-address to ddserver. As an alternative you can use your homerouter.

**Comment by intelyes** [comment]
root@cloud:~# netstat -anptl |grep 8080
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      3387/python     
root@cloud:~#

**Comment by reissmann** [comment]
This looks like ddserver is already running on port 8080 :)

When you start the init-script (/etc/init.d/ddserver start), then ddserver will run the command "ddserver-bundle" in the background. 

You can access the webinterface and send IP address updates, right? 
What exactly is not working right now?
