### ISSUE TITLE
Wrong redirect during registration

### ISSUE THREAD

**Issue by fooker** [ddserver/ddserver#8]
After entering an illegal password, you will be redirected to the login page instead of the validation page.

**Comment by reissmann** [comment]
Fixing with help of session.

Other issue: When adding an account and the activation mail doesn't get sent, no authcode is in the db. Now, when submitting a password on the activate page providing the correct username and an arbitrary authcode, an error is shown, but the user is logged in.

**Comment by reissmann** [comment]
Can't reproduce the other issue. Seems fine.
