### ISSUE TITLE
Getting IPv6 Address when using DualStack

### ISSUE THREAD

**Issue by mortzel** [ddserver/ddserver#89]
Calling https://ddserver.org/nic/ip ,when using dualstack, shows the ipv4 address. This causes ddclient to not work properly. 

```
RECEIVE:  2003:c5:bbbf:1660:d54b:4f39:e338:5e3d
DEBUG:    get_ip: using web, https://ddserver.org/nic/ip reports <undefined>
WARNING:  unable to determine IP address
```

**Comment by reissmann** [comment]
Use http://ipv4.ddserver.org/nic/ip to force an IPv4 connection or http://ipv6.ddserver.org/nic/ip for IPv6
