### ISSUE TITLE
badauth 

### ISSUE THREAD

**Issue by akront** [ddserver/ddserver#94]
Thank you for this amazing software.

been struggling to get this working for a couple of weeks now, no mattter what config changes I do it comes up with "badauth" always

ddserver.log
updater: Update request for ['ddns.hostname.com'] as x.x.x.x
updater: Update attempt with missing credentials
updater: Update responses: [badauth]

I am using openwrt client and ddserver is running behind HAProxy with ssl termination on front end 

Any suggestions?

Thank You

**Comment by akront** [comment]
I am trying to test on browser directly with:

https://admin:hostpassword@mydns.server.com/nic/update?hostname=test.mydns.server.com&myip=x.x.x.x

with the same result .

any help would be appreciated

**Comment by akront** [comment]
another note, I have tested locally https://admin:hostpassword@mydns.server.com:8080/nic/update?hostname=test.mydns.server.com&myip=x.x.x.x and also receive badauth

now I am in doubt if ddserver provides this auth or the proxy in front has to be configured with basic auth header?

If header is necessary what would be the header line to add to HAproxy 

Thank you

**Comment by reissmann** [comment]
Hey akront,

````updater: Update attempt with missing credentials````

This error message says that ddserver did not receive a username and/or password. It looks like HAProxy does not forward the HTTP basic authentication parameters to ddserver. I don't know HAProxy very well and a quick google search didn't bring up any hints.

Do you use HAProxy only to enable SSL/TLS support or is there another reason? Could you try to use apache2 or nginx as a reverse proxy to see if the problem is with HAProxy? Here is an example apache2 configuration, which should work:

````
<VirtualHost *:443>
        ServerName mydns.server.com

        ProxyPass / http://127.0.0.1:8080/
        ProxyPassReverse / http://127.0.0.1:8080/

        LogLevel warn
        ErrorLog /var/log/apache2/error.log
        CustomLog /var/log/apache2/ssl_access.log combined

        SSLEngine on
        SSLProtocol All -SSLv2 -SSLv3

        SSLCertificateFile /path/to/yourcert.pem
        SSLCertificateKeyFile /path/to/privkey.pem
</VirtualHost>
````

What version of ddserver do you currently use? Version 0.2 is shown as the latest stable release, however, version 0.3 is much more improved and is running on ddserver.org for over a year without any issues. It introduces a lot of fixes, and it is now using the pdns-remote-backend instead of the pipe backend. In version 0.3 an example apache2 configuration file is included, which would also allow to add SSL/TLS.

I'm sorry, I planned to finish work and release v0.3 a long time ago. If you want to give it a try, you'll have to clone the git repo, switch to branch 0.3-dev, and then install as usual. The idea in v0.3 is to install into a virtualenv. If you encounter errors installing it, I'm happy to help.

There is also documentation for 0.3, which is not yet merged. You can find it here (all .adoc files can be viewed directly in github): https://github.com/ddserver/ddserver/tree/feature/62/ddserver/resources/doc/manual

Regards, Sven.

**Comment by fooker** [comment]
> another note, I have tested locally https://admin:hostpassword@mydns.server.com:8080/nic/update?hostname=test.mydns.server.com&myip=x.x.x.x and also receive badauth

This is a common problem if you test with a browser. Modern browser do not send any credentials if not explicitly asked by the server. The update API does not do that, as it is not part of the update protocol and never meant for human interaction. You can use `curl` or some other tool to send the exact request.

> now I am in doubt if ddserver provides this auth or the proxy in front has to be configured with basic auth header?
> If header is necessary what would be the header line to add to HAproxy

You need to forward the `Authentication` Header from the client through the proxy to the `ddserver` instance unchanged. More details about the required header can be found here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Basic_authentication_scheme

**Comment by akront** [comment]
Thanks, I will try tweaking the header, however as Sven pointed out might be worth to do a clean install with 0.3 as this seems working well at ddserver.org with the new method of putting username and password at the end of the URL. I have tried the old method at  ddserver.org and receive badauth as well.

**Comment by akront** [comment]
Thanks, I will try tweaking the header, however as Sven pointed out might be worth to do a clean install with 0.3 as this seems working well at ddserver.org with the new method of putting username and password at the end of the URL. I have tried the old method at  ddserver.org and receive badauth as well.

**Comment by akront** [comment]
Spent the last few days building a clean VM , everything works ok Powerdns wise but there is no dns resolution from ddserver to the subzones I create.

there is some problem with the ddserver remove backend. Not sure how to take it from here, any help would be appreciated 

 service pdns monitor
 Reading random entropy from '/dev/urandom'
'/usr/lib/x86_64-linux-gnu/pdns/libbindbackend.so'
[bind2backend] This is the bind backend version 4.1.1 reporting
Loading '/usr/lib/x86_64-linux-gnu/pdns/libgmysqlbackend.so'
 [gmysqlbackend] This is the gmysql backend version 4.1.1 reporting
 Loading '/usr/lib/x86_64-linux-gnu/pdns/libremotebackend.so'
 [RemoteBackend] This is the remote backend version 4.1.1 reporting
This is a standalone pdns
Unable to bind UDP socket to '0.0.0.0:53': Address already in use
Fatal error: Unable to bind to UDP socket

it seems because power dns is listening on 53 ddserver can't start and listen on the same port?

**Comment by reissmann** [comment]
How did you configure the ddserver remote-backend? It should not run as a standalone service, but as a pdns backend (see: https://github.com/ddserver/ddserver/blob/feature/62/ddserver/resources/doc/manual/admin.adoc)

The error message sounds more like pdns itself is unable to bind to :53. Are you sure there is no other service running on that port? You can check using "netstat -ul" or "ss -ul" to check.

**Comment by akront** [comment]
I did exactly as the manual says, I've put 👍 
launch=+remote
remote-connection-string=pipe:command=/opt/ddserver/bin/ddserver-recursor

on the /etc/powerdns/pdns.d/pdns.local.gmysql.conf as an aditional backend. is this correct? I used launch+=remote because pdns doesnt start with launch=+

I tried to do inside the /etc/powerdns/pdns.conf on the launch= but then pdns service doesnt start because of the + , removing it pdns starts but still the subzone is not responding to anything.

I might be doing something wrong, but I believe was like this that was working on a old VM with a pipe command instead of remote backend

**Comment by akront** [comment]
The standalone line I believe it referes to the powerdns installation as being standalone instead of cluster..


I have an old VM running ddserver 0.2 with pipe instead of remote backend configured on /etc/powerdns/pdns.d/pdns.local.gmysql.conf and resolves the subzone fine the problem is the updating that doesnt work, hence I looked foward to create a new VM and use the new method of updating the URL with user and password at the end

**Comment by akront** [comment]
This is how I have /etc/powerdns/pdns.d/pdns.local.gmysql.conf

# MySQL Configuration
#
# Launch gmysql backend
launch+=gmysql,remote
remote-connection-string=pipe:command=/opt/ddserver/bin/ddserver-recursor

# gmysql parameters
gmysql-host=localhost
gmysql-port=3306
gmysql-dbname=pdns
gmysql-user=pdns
gmysql-password=xxxx
gmysql-dnssec=yes
# gmysql-socket=

**Comment by akront** [comment]
service pdns status
● pdns.service - PowerDNS Authoritative Server
   Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-06-22 00:13:38 BST; 4min 4s ago
     Docs: man:pdns_server(1)
           man:pdns_control(1)
           https://doc.powerdns.com
 Main PID: 17637 (pdns_server)
    Tasks: 15 (limit: 975)
   CGroup: /system.slice/pdns.service
           ├─17637 /usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --write-pid=no
           ├─17677 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor
           └─17679 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor

**Comment by akront** [comment]
everything seems fine, pdns resolves all zones that I have, however the subzone in ddserver  doesnt resolve anything 

i have in pdns domain.com , all records resolve fine

on ddserver I have dynamic.domain.com , however no records on this zone are resolved by pdns.

maybe I am missing something on the ddserver config , do I need to activate anything specifically on /etc/ddserver/ddserver.conf to tell pdns to resove the records in the subzone ?

thank you

**Comment by akront** [comment]
turned debugging on, in all honesty i think the recursor is working as it should, is showing on the pdns service as working fine it seems, but debug says cannot find the zone 

pdns.service - PowerDNS Authoritative Server
   Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-06-22 00:32:52 BST; 57s ago
     Docs: man:pdns_server(1)
           man:pdns_control(1)
           https://doc.powerdns.com
 Main PID: 22407 (pdns_server)
    Tasks: 16 (limit: 975)
   CGroup: /system.slice/pdns.service
           ├─22407 /usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --write-pid=no
           ├**─22506 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor
           ├─22510 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor
           └─22511 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor**

Jun 22 00:33:45 DynDNS pdns_server[22407]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and typ
Jun 22 00:33:45 DynDNS pdns_server[22407]: request: {u'remote': u'192.168.1.5', u'local': u'192.168.1.2', u'qname': u'test.dynamic.domain.com.',
Jun 22 00:33:45 DynDNS pdns_server[22407]: Lookup for 'ANY' of 'test.dynamic.domain.com' within zoneID 8
Jun 22 00:33:45 DynDNS pdns_server[22407]: Found no authoritative zone for test.dynamic.domain.com

**Comment by akront** [comment]
The listening problem seems a bug on ubuntu 18 LTS, it doesnt happen on 16

Listening conflict between systemd-resolved and pdns since systemd 231

https://github.com/PowerDNS/pdns/issues/4505

if we disable systemd  pdns works ok bind to 0.0.0.0, as I need the system resolver i've bind pdns to the NIC IP so systemd and pdns are working both fine

to answer your question this is what netstat  says 

 netstat -tapn|grep 53
tcp        0      0 192.168.1.2:53           0.0.0.0:*               LISTEN      1419/pdns_server
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      765/systemd-resolve
tcp6       0      0 :::53                   :::*                    LISTEN      1419/pdns_server

pdns resolves all my records on the pdns database, however the delegation to ddservers seems not working, I'm pretty sure I am missing something on ddserver config or something simillar to make ddserver resolve the subzone

**Comment by reissmann** [comment]
Oh, thats a bunch of new comments :)

The most interesting here is:
````
Jun 22 00:33:45 DynDNS pdns_server[22407]: Query: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and typ
Jun 22 00:33:45 DynDNS pdns_server[22407]: request: {u'remote': u'192.168.1.5', u'local': u'192.168.1.2', u'qname': u'test.dynamic.domain.com.',
Jun 22 00:33:45 DynDNS pdns_server[22407]: Lookup for 'ANY' of 'test.dynamic.domain.com' within zoneID 8
Jun 22 00:33:45 DynDNS pdns_server[22407]: Found no authoritative zone for test.dynamic.domain.com
````

This says that ddserver backend is running and getting requests by powerdns. However, powerdns thinks that it is not authoritive for dynamic.domain.com.

If you use dig to query dns, do you get any result for the following commands?
````
dig SOA dynamic.domain.com
dig NS dynamic.domain.com
````
And does the result point to your server?


For ddserver.org I am using the pdns simplebind backend to deliver the basic ddserver.org zone containing the SOA, NS, MX and some static A and AAAA records (/etc/powerdns/zones/ddserver.org.zone):
````
$ORIGIN ddserver.org.
$TTL 3600

@					IN	SOA		ns.open-networx.org. hostmaster.open-networx.org. (
								2342420043 ; serial
								43200      ; refresh (12 hours)
								7200       ; retry (2 hours)
								604800     ; expire (1 week)
								43200      ; minimum (12 hours)
								)

@			3600	IN	NS		ns1.open-networx.org.
						NS		ns2.open-networx.org.

www						A		...
[...]
````
All subdomains managed by the ddserver app must not be present in this zone file!

In /etc/powerdns/pdns.d/bind.conf just say:
````
launch+=bind
bind-config=/etc/powerdns/bindbackend.conf
````

In the pdns simplebind backend configuration (/etc/powerdns/bindbackend.conf):
````
zone "ddserver.org" {
        type master;
        file "/etc/powerdns/zones/ddserver.org.zone";
};
````

By this, pdns knows to be authoritive for the zone. All dynamic records are fetched from ddserver via the remote backend.

Instead of using the simplebind backend, you can of course use the mysql backend for the zone skeleton.

Note: ddserver-0.2 is not compatible with the remote-backend, but only with the pipe-backend.

Hope this helps. Waiting for your feedback :)

**Comment by reissmann** [comment]
Looks like I actually never documented this. Sorry :)

**Comment by akront** [comment]
Hello,

Been trying virtually everything but there is no way I can get the subdomain records to respond. 

If I may ask, did you had a chance to test the remote backend working as expected at some point of the 0.3 development ?

I get:

dig SOA dynamic.domain.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> SOA dynamic.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50632
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;dynamic.domain.com.         IN      SOA

;; Query time: 23 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 26 10:40:36 UTC 2018
;; MSG SIZE  rcvd: 50
----------------------------------------------------

 dig NS dynamic.domain.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> NS dynamic.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23532
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;dynamic.domain.com.         IN      NS

;; ANSWER SECTION:
dynamic.domain.com.  3600    IN      NS      ns1.domain.com.
dynamic.domain.com.  3600    IN      NS      ns2.domain.com.

;; Query time: 7 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 26 10:41:05 UTC 2018
;; MSG SIZE  rcvd: 86

I tried to create the Bind backend, but I seems I cannot use the bind backend and the mySQL backend at the same time, so that would defeat the purpose.

The reason I am using mysql backend is because I use a WebUI to insert the records into pdns, and the ddserver ui to put the records into the ddserver database, everything works perfectly apart from ddserver responding to the subdomain records.

What is most interesting is the old vm with 0.2 responds fine using the pipebackend, so must be something related with either the setup or the remote backend is not getting data back from ddserevr DB

I can arrange SSH access if you fancy to have a look. ddserver is one of the few if not the only to execute the kind of job I was looking for privately under my server control.

Thank you

**Comment by akront** [comment]
netstat -tapn|grep 53

tcp        0      0 192.168.1.5:53            0.0.0.0:*               LISTEN      34004/pdns_server
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      916/systemd-resolve
tcp        0      0 127.0.0.1:34538         127.0.0.1:3306          ESTABLISHED 34045/python
tcp        0      0 127.0.0.1:34536         127.0.0.1:3306          ESTABLISHED 34042/python
tcp        0      0 192.168.1.5:53            52.53.250.225:41676     CLOSE_WAIT  34382/python

I assume you running ubuntu or debian?  do you face this conflict issue between systemd-resolve and pdns_server?

I wonder this conflict is the cause for pdns not retrieving data from ddserver or not responding to the subzone..

**Comment by akront** [comment]
on old VM I have  pdns_server[4956]: Jun 26 12:16:56 Backend launched with banner: OK        ddserver
this should be expected also on new VM with remote backend ?

 netstat -tapn|grep 53
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      4956/pdns_server
tcp6       0      0 :::53                   :::*                    LISTEN      4956/pdns_server

**Comment by akront** [comment]
Interesting, I've build a brand new Debian VM with pdns and ddserver without systemd-resolve issue and still get  Jun 26 12:30:55 Found no authoritative zone for *.dynamic.domain.com

so I believe we can abandon that theory

I have a feeling remote back end could be part of the issue.

I am tempted to build a new VM with 0.2 and pipe to see if replies to the sub-zone.

however the setup I have the updater wont work with traditional URL

**Comment by reissmann** [comment]
Happy to hear that you like ddserver. Didn't find a tool either to do the job for me, thats why we created ddserver :)

I'm running the remote-backend (ddserver-0.3-dev) without any issues.
Did you configure an authoritive zone named dynamic.domain.com with the following contents?

````
dynamic.domain.com.  3600 IN SOA ns1.domain.com. hostmaster.domain.com. (
		2342420043 	43200 7200 604800 43200 )

dynamic.domain.com. 3600 IN NS ns1.domain.com.
dynamic.domain.com. 3600 IN NS ns2.domain.com.
````

This skeleton of the zone must be served by powerdns using any backend (except ddserver). I do it with the bind backend, but you can use the mysql backend as well. You would insert the following into the pdns database:
````
INSERT INTO domains (name, type) VALUES ('dynamic.domain.com', 'NATIVE');
````
Use MASTER if you want NOTIFYs to be sent to slave dns servers, or NATIVE if you have a replicated backend (i.e., MySQL replication).

Then insert RRs:
````
INSERT INTO `records` (`domain_id`, `name`, `type`, `content`, `ttl`, `prio`, `change_date`, `disabled`, `ordername`, `auth`) VALUES
(52, 'dynamic.domain.com', 'SOA', 'ns1.domain.com. hostmaster.domain.com. 1526379277 10800 1800 1209600 86400', 86400, 0, NULL, 0, NULL, 1),
(52, 'dynamic.domain.com', 'NS', 'ns1.domain.com', 86400, 0, NULL, 0, NULL, 1),
(52, 'dynamic.domain.com', 'NS', 'ns2.domain.com', 86400, 0, NULL, 0, NULL, 1);
````
Then you should be able to do the SOA query, independently from the ddserver backend.
As soon as the domain is known to pdns as a master/native domain, it will also ask the ddserver backend for resource records.

If you already did all this or it still does not work, could you please check and post the pdns and ddserver log again?

**Comment by akront** [comment]
I managed to get the bind backend working along with the mysql backend.

again all records on mysql backend resolve as well all records on bind backend file resolve fine.

no subdomain records resolve at all from the ddserver database.

 dig SOA  dynamic.domain.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> SOA dynamic.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18707
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;dynamic.domain.com.         IN      SOA

;; ANSWER SECTION:
dynamic.domain.com.  3599    IN      SOA     ns1.domain.com. hostmaster.domain.com. 2018062602 10800 3600 604800 3600

;; Query time: 21 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 26 22:47:22 UTC 2018
;; MSG SIZE  rcvd: 101
------------------------------------------------------------------------------------------

dig NS  dynamic.domain.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> NS dynamic.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20660
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;dynamic.domain.com.         IN      NS

;; ANSWER SECTION:
dynamic.domain.com.  3599    IN      NS      ns1.domain.com.
dynamic.domain.com.  3599    IN      NS      ns2.domain.com.

;; Query time: 31 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 26 22:50:04 UTC 2018
;; MSG SIZE  rcvd: 86

again everything seems perfect with all the required conditions so the ddserver recursor replies, but it doesnt it seems dead.

this record in theory should reply the ip that is on the ddserver database

dig A test.dynamic.domain.com

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> A test.dynamic.domain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 1326
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;test.dynamic.domain.com.     IN      A

;; Query time: 29 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jun 26 22:52:30 UTC 2018
;; MSG SIZE  rcvd: 54

I am convicend has nothing to do with being bind backend or remote backend, both work fine. 

pdns.service - PowerDNS Authoritative Server
   Loaded: loaded (/lib/systemd/system/pdns.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-06-26 22:46:14 UTC; 9min ago
     Docs: man:pdns_server(1)
           man:pdns_control(1)
           https://doc.powerdns.com
 Main PID: 1808 (pdns_server)
    Tasks: 16 (limit: 9448)
   CGroup: /system.slice/pdns.service
           ├─1808 /usr/sbin/pdns_server --guardian=no --daemon=no --disable-syslog --log-timestamp=no --write-pid=no
           ├─1927 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor
           ├─1931 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor
           └─1980 /opt/ddserver/bin/python /opt/ddserver/bin/ddserver-recursor
------------------------------------------------------------------------------------------
request: {u'remote': u'74.125.47.129', u'local': u'192.168.1.5', u'qname': u'*.dynamic.domain.com.', u'real-remote': u'74.125.47.129/32', u'zone-id': 10, u'qtype': u'ANY'}


now the message found no authoritative servers for the zone dynamic.domain.com doesnt appear, because the zone is there, problem is record doesnt get served from ddserver recursor/database


Manage hostnames

Hostname | IPv4 Address | IPv6 Address | Last update | Actions
-- | -- | -- | -- | --
test.dynamic.domain.com | 2.2.2.2 | (No address assigned) | 2018-06-24 16:16:15

is really puzzling why it doesnt retrieve the record, I've exhausted my thinking ;)

**Comment by reissmann** [comment]
Uhhhm ... something else came into my mind ... Are you using a pdns version >= 4?

There is a compatibility issue starting with version 4, which I patched manually on ddserver.org, but never merged the patch into version 0.3-dev (see issue #93).

I committed the changes to 0.3-dev a second ago. You can just pull and reinstall (rerun the setup script) to apply the changes.

**Comment by reissmann** [comment]
Or if you want quick and dirty test, you can edit the python file by hand.

Did you install with or without python virtual env?

Without venv, the path is something like:
````
/usr/local/lib/python*/dist-packages/ddserver-0.3_dev-py*.egg/ddserver/recursor/__main__.py
````

This is what needs to be changed:
https://github.com/reissmann/ddserver/commit/13e2ce63ddd6c03b1f70441098d111fd32d8a19a

**Comment by akront** [comment]
Yes I am using PowerDNS 4.1.1, I removed /opt/ddserver and reinstalled, but same problem no resolution of subbzone records, not sure if this way was clean but seems it was installed fresh.

I have arranged SSH access if you fancy to have a look, I have no more options to get this to work as I virtually tried everything that we discussed 

please check the ddserver.org inbox for details 

thank you

**Comment by akront** [comment]
Thanks for fixing the issue
